export const LESSON_SELECTED = 'LESSON_SELECTED'
export const LESSON_CLOSED = 'LESSON_CLOSED'
export const SITE_NAME = 'Learning Map'
export const SITE_TITLE_CLASS = 'cl-site-title'
export const NODES_ADDED = 'NODES_ADDED'
